[package]
name = "slha-derive"
version = "0.1.0"
authors = ["Torsten Weber <tweber@physik.rwth-aachen.de>"]
license = "MIT/Apache-2.0"
repository = "https://github.com/tweber12/slha-rs"

[lib]
proc_macro = true

[dependencies]
syn = "*"
quote = "*"
